services:
  nickel:
    container_name: nickel
    build: .
    environment:
      - PORT=8006
    ports:
      - "8006:8006"
    volumes:
      - ./keys.json:/app/keys.json:ro
    restart: unless-stopped
